### ISSUE TITLE
Allow to `close` staging repo without `release`

### ISSUE THREAD

**Issue by abelsromero** [spring-io/concourse-release-scripts#22]
Current MavenCentral publish method does a full release which does not allow to make any validation (for example, when setting a publication for first time or doing heavy publication changes).
It would be interesting to have an option to avoid releasing so user can push the artifacts and trigger MavenCentral's validation on close without releasing if everything is OK.

If we don't want to break backward compatibilty, we could have a flag `autoRelease` with default to true. But ideally I think it'd be nice to have 2 commands one for publication and another for release.

**Comment by bclozel** [comment]
Right now, the publish command does the following:

1. Create a staging repository on Sonatype
2. Deploying artifacts in that repository
3. Closing the staging repository (Sonatype validation happens here)
4. Releasing the staging repository

So you'd like to make step 4) optional? Make it a separate command? Or just leave it as a manual operation on the Sonatype infra directly?

IIRC, this feature was discussed within the Spring Boot team but we've found that any verification should happen during the first staging on the artifactory infra, and that we can't catch any more possible mistakes after Sonatype's automated checks.

**Comment by abelsromero** [comment]
> So you'd like to make step 4) optional? Make it a separate command? Or just leave it as a manual operation on the Sonatype infra directly?

Just optional, so one can validate that everything is fine. For example, checking for a newly created artifact or after heavy build changes (e.g. maven-2-gradle change).


> IIRC, this feature was discussed within the Spring Boot team but we've found that any verification should happen during the first staging on the artifactory infra, and that we can't catch any more possible mistakes after Sonatype's automated checks.

I agree with it, but truth is that artifactory accepts artifacts that then fail in Sonatype, leaving you with 2 options: create a new minor and try again, or delete the artifact from release hoping no one saw it.
In Sonatype is possible to close the staging repo and then drop it, allowing to verify it without releasing. So teh practical approach is to deploy+close+drop untill everything is fine, but that's not possible using `concourse-release-scripts`. In our case I resorted to run a locally modified version.
